### ISSUE TITLE
[ Model ] 데이터셋 자동 다운로더 작업

### ISSUE THREAD

**Issue by BeautterLife** [kookmin-sw/capstone-2021-23#2]
- python selenium 라이브러리를 사용하여 AI Hub 공공 데이터셋 자동 다운로더 구축 작업

**Comment by BeautterLife** [comment]
- css_selector로 페이지 접근중 에러 발생 : **css_selector는 웹 페이지 접근할 때 마다 새로운 값으로 변경됨**
   => XPath로 접근해보는 방법 시도

**Comment by BeautterLife** [comment]
> * css_selector로 페이지 접근중 에러 발생 : **css_selector는 웹 페이지 접근할 때 마다 새로운 값으로 변경됨**
>   => XPath로 접근해보는 방법 시도

데이터셋 a 태그 값을 print해보니 session정보가 포함된것을 확인함
=> 데이터셋 하나 또는 두개를 다운받고 전처리한 후에는 session이 종료될 수 있어서 session에 영향받지 않는 코드를 작성해야함

**Comment by BeautterLife** [comment]
# 세션 관련

로그인하면 서버로부터 받은 토큰이 쿠키로 저장됨.
쿠키에 세션 정보가 있는데 일정 시간(1시간 이내)이후엔 유효하지 않은 세션이 됨.
데이터셋 다운로드 링크의 css selector에 세션정보가 있어서 미리 크롤링 해 둔 링크 정보는 세션이 만료되면 유효하지 않음.
어짜피 로그인 세션도 데이터 전처리 하는 도중에 만료되므로 매번 전체 데이터셋 다운로드 링크 정보를 가지고 있다가,
전역변수로 다음으로 다운받을 링크를 알아내는 방법으로 작성했으나,
**XPath**를 이용하면 고정된 링크를 알 수 있을것 같아 추후에 시도해 볼 예정.

**Comment by taehyeon4** [comment]
1. python selenium 라이브러리를 사용하여 데이터셋 다운로드 자동화
>  data_list[][] 구조가 크기가 1인 1차원 배열이 189개 있는 2차원 배열로 확인됨. 이에 맞춰 코드 수정 작업 완료. 다운로드가 완료된 크롬 브라우저가 종료되지 않는 문제점이 있었는데, 코드 수정 작업을 통해 이 문제 역시 해결됨(코드가 의도대로 동작하지 못해 driver.close()까지 도달하지 못했음).

2. ffmpeg 프레임 워크를 이용한 화질 줄이기
> 다운로드 받아야 하는 데이터 양이 TB 단위이기 때문에 영상 화질을 줄여서 보관하기로 결정. 데이터를 다운로드 하는 시간보다 영상 화질을 줄이는 과정이 시간이 더 소요됨. gpu를 활용해서 속도를 개선할 수 있을 듯 하지만, gpu를 활용하지 않고도 대략 일주일이면 모든 데이터셋 화질을 낮출 수 있고 이후 추가적으로 화질을 낮추는 작업은 필요하지 않을 것으로 판단되기 떄문에 현재 안정적으로 실행되는 방법을 계속 사용.(향후 ffmpeg로 더 많은 작업이 필요하다면 gpu를 활용하는 방법을 테스트 할 예정)

3. 1,2 과정을 동시에 진행해주는 하나의 자동화 프로그램 개발 (1,2 과정이 서로 꼬이지 않도록 필요시 대기해주는 코드를 포함)

----
데이터셋 구축을 위한 자동화 작업이 마무리 되었고, 순조롭게 진행되고 있음.
